{% set name = "CoastSeg" %}
{% set version = "1.1.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: ce98f919b9d5512e5f0e62e98a2d6b35df09f259bab70d9d4a2bba93dfc96e54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - earthengine-api >=0.1.388
    - pytmd
    - xarray
    - python >=3.9
    - aiohttp
    - area
    - chardet
    - coastsat-package >=0.1.43
    - dask-core
    - doodleverse-utils >=0.0.35
    - geojson
    - geopandas
    - ipyfilechooser >=0.6.0
    - ipywidgets >=8.0.6
    - leafmap >=0.14.0
    - nest-asyncio
    - tensorflow
    - tqdm
    - transformers

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Doodleverse/CoastSeg
  summary: An interactive jupyter notebook for downloading satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
