{% set name = "CoastSeg" %}
{% set version = "1.1.37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: 439e5f4f2cb8433c73fd2c6e008414b31224fd98cf9f745511b45f453076d3fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=61.0
    - pip
  run:
    - python >=3.10
    - area
    - aiohttp
    - chardet
    - coastsat-package >=0.1.43
    - dask-core
    - doodleverse-utils >=0.0.35
    - earthengine-api >=0.1.388
    - geojson
    - geopandas
    - jupyterlab >=3.0.0
    - leafmap >=0.14.0
    - nest-asyncio
    - pytmd
    - transformers
    - xarray

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Doodleverse/CoastSeg
  summary: An interactive jupyter notebook for downloading satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
