{% set name = "CoastSeg" %}
{% set version = "1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: cb08a4c05e4c60a9d4b2d7fe3b62d93776bb1ae5a4d86294ab8bfee9daa46581

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - pooch
    - python >={{ python_min }}
    - gdal >=3.8.4
    - h5py >=3.10.0
    - pytmd >=2.1.7
    - coastsat-package >=0.1.74
    - area
    - aiohttp
    - chardet
    - dask-core
    - doodleverse-utils >=0.0.35
    - earthengine-api >=0.1.388
    - geojson
    - geopandas
    - jupyterlab >=3.0.0
    - leafmap >=0.14.0
    - nest-asyncio
    - xarray

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SatelliteShorelines/CoastSeg
  doc_url: https://satelliteshorelines.github.io/CoastSeg/
  dev_url: https://github.com/SatelliteShorelines/CoastSeg
  summary: An interactive python package for satellite derived shoreline workflows
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
