{% set name = "CoastSeg" %}
{% set version = "0.0.74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: 2cdfca6ce5f7bc4fc4ca471f54cf0b43c096bf3f8ae1c35d69ac8011b231545a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - aiohttp
    - area
    - chardet
    - coastsat-package >=0.1.13
    - dask-core
    - doodleverse-utils >=0.0.35
    - geojson
    - geopandas
    - ipyfilechooser >=0.6.0
    - ipywidgets >=8.0.6
    - leafmap >=0.14.0
    - nest-asyncio
    - tensorflow
    - tqdm
    - transformers

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Doodleverse/CoastSeg
  summary: An interactive jupyter notebook for downloading satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
