{% set name = "CoastSeg" %}
{% set version = "1.1.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coastseg-{{ version }}.tar.gz
  sha256: ac1be6b7913f484e6d622ead2071d1108698d5408ed0b98e242d72a95a40ce79

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - earthengine-api >=0.1.388
    - coastsat-package >=0.1.43
    - geopandas
    - jupyterlab >=3.0.0
    - area
    - doodleverse-utils >=0.0.35
    - ipyfilechooser >=0.6.0
    - tqdm
    - leafmap >=0.14.0
    - geojson
    - aiohttp
    - nest-asyncio
    - tensorflow
    - dask-core
    - ipywidgets >=8.0.6
    - transformers
    - chardet
    - xarray
    - pytmd

test:
  imports:
    - coastseg
  commands:
    # bogus requirement on versioneer in doodleverse_utils
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Doodleverse/CoastSeg
  summary: An interactive jupyter notebook for downloading satellite imagery
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
